USE topzyn;

ALTER TABLE account
  ADD COLUMN IF NOT EXISTS phone_number VARCHAR(20) NULL AFTER email,
  ADD COLUMN IF NOT EXISTS total_top_up BIGINT UNSIGNED NOT NULL DEFAULT 0 AFTER role;

CREATE TABLE IF NOT EXISTS topup_transaction (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  account_id BIGINT NOT NULL,
  product_code VARCHAR(60) NOT NULL,
  amount BIGINT UNSIGNED NOT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'success',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_topup_transaction_account
    FOREIGN KEY (account_id) REFERENCES account(id)
    ON DELETE CASCADE
);

